import { Bell, CheckCheck, Mail } from "lucide-react";
import { PageHeader } from "../components/PageHeader";
import { EmptyState } from "../components/ui";
import type { Role } from "../domain/types";
import { formatDateTime } from "../lib/format";
import { useAppStore } from "../store/appStore";

export function NotificationsPage({ role }: { role: Role }) {
  const user = useAppStore((state) => state.currentUser());
  const allNotifications = useAppStore((state) => state.notifications);
  const notifications = allNotifications.filter(
    (item) =>
      item.recipientRole === role &&
      (!item.recipientId || item.recipientId === user?.workerId)
  );
  const markRead = useAppStore((state) => state.markNotificationRead);

  return (
    <div>
      <PageHeader
        eyebrow="Communication log"
        title="Updates"
        description="Notices and simulated email events generated by activity in the prototype."
      />
      <div className="mt-7 rounded-[24px] border border-slate-200 bg-white p-3 shadow-[0_18px_55px_rgba(16,42,67,0.05)] sm:p-5">
        {notifications.length === 0 ? (
          <EmptyState
            title="No notifications"
            description="Updates relevant to this workspace will appear here."
          />
        ) : (
          <div className="divide-y divide-slate-100">
            {notifications.map((item) => (
              <button
                key={item.id}
                type="button"
                onClick={() => markRead(item.id)}
                className="flex w-full items-start gap-4 rounded-xl px-3 py-4 text-left transition hover:bg-slate-50"
              >
                <span
                  className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${
                    item.read
                      ? "bg-slate-100 text-slate-400"
                      : "bg-blue-50 text-blue-700"
                  }`}
                >
                  {item.channel === "email_simulation" ? (
                    <Mail size={18} />
                  ) : (
                    <Bell size={18} />
                  )}
                </span>
                <span className="min-w-0 flex-1">
                  <span className="flex flex-wrap items-center gap-2">
                    <strong className="text-sm text-[#102A43]">
                      {item.title}
                    </strong>
                    {!item.read && (
                      <span className="h-2 w-2 rounded-full bg-[#F97316]" />
                    )}
                  </span>
                  <span className="mt-1 block text-sm leading-6 text-slate-500">
                    {item.message}
                  </span>
                  <span className="mt-2 block text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-400">
                    {formatDateTime(item.createdAt)}
                  </span>
                </span>
                {item.read && (
                  <CheckCheck
                    size={17}
                    className="mt-1 shrink-0 text-emerald-600"
                    aria-label="Read"
                  />
                )}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
